package com.example.backend.can.service;

import com.example.backend.can.dto.CanSessionResponse;
import com.example.backend.can.dto.CarCatalogDto;
import com.example.backend.can.dto.CarCreateRequest;
import com.example.backend.can.dto.CarDto;
import com.example.backend.can.dto.CarUpdateRequest;
import com.example.backend.can.dto.RequirementDtos.CarRequirementDto;
import com.example.backend.can.entity.CarEntity;
import com.example.backend.can.entity.EcuCatalogEntity;
import com.example.backend.can.entity.RequirementSetEntity;
import com.example.backend.can.repository.CanSessionRepository;
import com.example.backend.can.repository.CarRepository;
import com.example.backend.can.repository.EcuCatalogRepository;
import com.example.backend.can.repository.IntegrityFaultRepository;
import com.example.backend.can.repository.RequirementSetRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Service layer for vehicle (Car) management.
 * Encapsulates all business logic for the car fleet feature.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class CarService {

    private final CarRepository carRepository;
    private final CanSessionRepository canSessionRepository;
    private final IntegrityFaultRepository integrityFaultRepository;
    private final CanSessionService canSessionService;
    private final EcuCatalogRepository ecuCatalogRepository;
    private final RequirementSetRepository requirementSetRepository;
    private final RequirementService requirementService;

    // ── Create ────────────────────────────────────────────────────────────────

    /**
     * Create a new car from a validated request.
     * carUid is auto-generated by CarEntity.prePersist() if not provided.
     *
     * @param request     validated create request (make, model, year required)
     * @param ownerUserId caller's user ID as BINARY(16) byte array — may be null
     * @return CarDto representing the saved car
     */
    @Transactional
    public CarDto createCar(CarCreateRequest request, byte[] ownerUserId) {
        CarEntity car = CarEntity.builder()
                .vin(request.getVin())
                .make(request.getMake())
                .model(request.getModel())
                .year(request.getYear())
                .color(request.getColor())
                .isVirtual(Boolean.TRUE.equals(request.getIsVirtual()))
                .isActive(true)
                .ownerUserId(ownerUserId)
                .build();

        CarEntity saved = carRepository.save(car);
        log.info("Car created: carUid={} make={} model={}", saved.getCarUid(), saved.getMake(), saved.getModel());
        return toDto(saved);
    }

    // ── Read ──────────────────────────────────────────────────────────────────

    /**
     * Get all active non-deleted cars owned by a specific user.
     *
     * @param ownerUserId user's binary(16) ID
     * @return list of CarDto (without computed stats)
     */
    public List<CarDto> getCarsByUser(byte[] ownerUserId) {
        return carRepository
                .findByOwnerUserIdAndIsActiveTrueAndDeletedAtIsNull(ownerUserId)
                .stream()
                .map(this::toDto)
                .toList();
    }

    /**
     * Get all active non-deleted cars (admin view), with computed stats
     * (sessionCount, totalFrames, lastSessionAt, faultRate) populated per car.
     *
     * @return list of CarDto ordered by creation date descending
     */
    public List<CarDto> getAllCars() {
        return carRepository.findAllActive()
                .stream()
                .map(car -> {
                    CarDto dto = toDto(car);
                    populateStats(dto, car.getId());
                    return dto;
                })
                .toList();
    }

    /**
     * Get a single car by its public UUID.
     * Throws 404 if not found or soft-deleted.
     *
     * @param carUid public UUID string
     * @return CarDto with computed stats populated
     */
    public CarDto getCarByUid(String carUid) {
        CarEntity car = findActiveByUid(carUid);
        CarDto dto = toDto(car);
        populateStats(dto, car.getId());
        return dto;
    }

    // ── Sessions ──────────────────────────────────────────────────────────────

    /**
     * List all CAN sessions belonging to a car identified by its public UUID.
     * Throws 404 if the car does not exist or is soft-deleted.
     *
     * @param carUid public UUID of the car
     * @return sessions ordered by createdAt DESC
     */
    public List<CanSessionResponse> getSessionsByCarUid(String carUid) {
        CarEntity car = findActiveByUid(carUid);
        return canSessionService.getSessionsByCarId(car.getId());
    }

    // ── Catalog assignment ────────────────────────────────────────────────────

    /**
     * List the catalogs assigned to a car (empty = car uses all catalogs).
     * Throws 404 if the car does not exist or is soft-deleted.
     */
    @Transactional(readOnly = true)
    public List<CarCatalogDto> getCarCatalogs(String carUid) {
        CarEntity car = findActiveByUidWithCatalogs(carUid);
        return car.getCatalogs().stream()
                .map(c -> new CarCatalogDto(c.getFilename(), c.getName(), c.getBusName()))
                .sorted((a, b) -> a.filename().compareToIgnoreCase(b.filename()))
                .toList();
    }

    /**
     * Replace a car's assigned catalog set with the given catalog filenames.
     * An empty list clears the assignment (car falls back to all catalogs).
     *
     * @throws ResponseStatusException 404 when the car is unknown,
     *                                 400 when a filename has no catalog record
     */
    @Transactional
    public List<CarCatalogDto> setCarCatalogs(String carUid, List<String> filenames) {
        CarEntity car = findActiveByUidWithCatalogs(carUid);

        java.util.Set<EcuCatalogEntity> resolved = new java.util.HashSet<>();
        for (String filename : filenames) {
            EcuCatalogEntity catalog = ecuCatalogRepository.findByFilename(filename)
                    .orElseThrow(() -> new ResponseStatusException(
                            HttpStatus.BAD_REQUEST, "Unknown catalog: " + filename));
            resolved.add(catalog);
        }

        car.getCatalogs().clear();
        car.getCatalogs().addAll(resolved);
        carRepository.save(car);
        log.info("Car {} catalogs set to {}", carUid,
                resolved.stream().map(EcuCatalogEntity::getFilename).toList());
        return getCarCatalogs(carUid);
    }

    // ── Requirement-set assignment (mirror of catalog assignment) ─────────────

    /**
     * List the requirement sets assigned to a car (empty = requirements engine
     * disabled for this car — no merged-global fallback, unlike catalogs).
     */
    @Transactional(readOnly = true)
    public List<CarRequirementDto> getCarRequirements(String carUid) {
        CarEntity car = findActiveByUidWithRequirements(carUid);
        return car.getRequirementSets().stream()
                .map(r -> new CarRequirementDto(r.getFilename(), r.getName(), r.getVersion()))
                .sorted((a, b) -> a.filename().compareToIgnoreCase(b.filename()))
                .toList();
    }

    /**
     * Replace a car's assigned requirement-set list with the given filenames.
     * An empty list clears the assignment (engine off for this car).
     *
     * @throws ResponseStatusException 404 when the car is unknown,
     *                                 400 when a filename has no registry record
     */
    @Transactional
    public List<CarRequirementDto> setCarRequirements(String carUid, List<String> filenames) {
        CarEntity car = findActiveByUidWithRequirements(carUid);

        java.util.Set<RequirementSetEntity> resolved = new java.util.HashSet<>();
        for (String filename : filenames) {
            // Registry rows are created on upload/save/reload — but a valid file
            // already on disk (seeded, or predating the registry table) may have
            // no row yet, so sync it from disk instead of rejecting it.
            RequirementSetEntity set = requirementSetRepository.findByFilename(filename)
                    .or(() -> requirementService.ensureRegistered(filename))
                    .orElseThrow(() -> new ResponseStatusException(
                            HttpStatus.BAD_REQUEST, "Unknown requirement set: " + filename));
            resolved.add(set);
        }

        car.getRequirementSets().clear();
        car.getRequirementSets().addAll(resolved);
        carRepository.save(car);
        log.info("Car {} requirement sets set to {}", carUid,
                resolved.stream().map(RequirementSetEntity::getFilename).toList());
        return getCarRequirements(carUid);
    }

    private CarEntity findActiveByUidWithRequirements(String carUid) {
        return carRepository.findByCarUidWithRequirements(carUid)
                .filter(c -> c.getDeletedAt() == null)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND, "Car not found: " + carUid));
    }

    /**
     * Catalog filenames assigned to a car, for the simulator start path.
     * Returns an empty list when the car is unknown or has no assignment —
     * in both cases the simulator uses all catalogs (legacy behaviour).
     */
    @Transactional(readOnly = true)
    public List<String> getAssignedCatalogFilenames(String carUid) {
        return carRepository.findByCarUidWithCatalogs(carUid)
                .filter(c -> c.getDeletedAt() == null)
                .map(c -> c.getCatalogs().stream()
                        .map(EcuCatalogEntity::getFilename)
                        .sorted()
                        .toList())
                .orElse(List.of());
    }

    private CarEntity findActiveByUidWithCatalogs(String carUid) {
        return carRepository.findByCarUidWithCatalogs(carUid)
                .filter(c -> c.getDeletedAt() == null)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND,
                        "Car not found: " + carUid
                ));
    }

    // ── Stats ─────────────────────────────────────────────────────────────────

    /**
     * Populate sessionCount, totalFrames, lastSessionAt, and faultRate
     * on an existing CarDto using aggregation queries.
     *
     * @param dto   the CarDto to enrich
     * @param carId internal DB id of the car
     */
    public void populateStats(CarDto dto, Long carId) {
        // JPQL aggregate queries return List<Object[]>
        // Each Object[] contains: [COUNT (Long), SUM (Long), MAX (LocalDateTime)]
        List<Object[]> results = canSessionRepository.getCarSessionStats(carId);

        if (results == null || results.isEmpty()) return;

        Object[] row = results.get(0);
        if (row == null || row.length < 3 || row[0] == null) return;

        try {
            long sessionCount = ((Number) row[0]).longValue();
            long totalFrames  = row[1] != null ? ((Number) row[1]).longValue() : 0L;
            LocalDateTime lastSessionAt = row[2] instanceof LocalDateTime ldt ? ldt : null;

            dto.setSessionCount((int) sessionCount);
            dto.setTotalFrames(totalFrames);
            dto.setLastSessionAt(lastSessionAt);

            // Fault rate: faults per 1000 frames
            if (totalFrames > 0) {
                long totalFaults = integrityFaultRepository.countFaultsByCarId(carId);
                dto.setFaultRate((double) totalFaults / totalFrames * 1000.0);
            }
        } catch (Exception e) {
            log.warn("Could not populate stats for carId={}: {}", carId, e.getMessage());
        }
    }

    // ── Update ────────────────────────────────────────────────────────────────

    /**
     * Update a car's mutable fields (PATCH semantics — only non-null fields applied).
     *
     * @param carUid  public UUID of the car to update
     * @param request fields to update (all optional)
     * @return updated CarDto
     */
    @Transactional
    public CarDto updateCar(String carUid, CarUpdateRequest request) {
        CarEntity car = findActiveByUid(carUid);

        if (request.getVin()      != null) car.setVin(request.getVin());
        if (request.getMake()     != null) car.setMake(request.getMake());
        if (request.getModel()    != null) car.setModel(request.getModel());
        if (request.getYear()     != null) car.setYear(request.getYear());
        if (request.getColor()    != null) car.setColor(request.getColor());
        if (request.getIsVirtual() != null) car.setIsVirtual(request.getIsVirtual());
        if (request.getIsActive()  != null) car.setIsActive(request.getIsActive());

        CarEntity saved = carRepository.save(car);
        log.info("Car updated: carUid={}", carUid);
        return toDto(saved);
    }

    // ── Delete (soft) ─────────────────────────────────────────────────────────

    /**
     * Soft-delete a car by setting deletedAt and isActive = false.
     * Sessions and frames are NOT deleted — historical data is preserved.
     *
     * @param carUid public UUID of the car to soft-delete
     */
    @Transactional
    public void softDeleteCar(String carUid) {
        CarEntity car = findActiveByUid(carUid);
        car.setDeletedAt(LocalDateTime.now());
        car.setIsActive(false);
        carRepository.save(car);
        log.info("Car soft-deleted: carUid={}", carUid);
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    /**
     * Find an active (non-deleted) car by carUid or throw 404.
     */
    private CarEntity findActiveByUid(String carUid) {
        return carRepository.findByCarUid(carUid)
                .filter(c -> c.getDeletedAt() == null)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND,
                        "Car not found: " + carUid
                ));
    }

    /**
     * Map CarEntity to CarDto (without computed stats).
     * Computed fields (sessionCount, totalFrames, faultRate) are left null
     * and populated separately by populateStats() when needed.
     */
    private CarDto toDto(CarEntity car) {
        return CarDto.builder()
                .carUid(car.getCarUid())
                .vin(car.getVin())
                .make(car.getMake())
                .model(car.getModel())
                .year(car.getYear())
                .color(car.getColor())
                .isVirtual(car.getIsVirtual())
                .isActive(car.getIsActive())
                .createdAt(car.getCreatedAt())
                .build();
    }
}
