package com.example.backend.can.service;

import com.example.backend.can.dto.CarCreateRequest;
import com.example.backend.can.dto.CarDto;
import com.example.backend.can.dto.CarUpdateRequest;
import com.example.backend.can.entity.CarEntity;
import com.example.backend.can.repository.CanSessionRepository;
import com.example.backend.can.repository.CarRepository;
import com.example.backend.can.repository.IntegrityFaultRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Service layer for vehicle (Car) management.
 * Encapsulates all business logic for the car fleet feature.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class CarService {

    private final CarRepository carRepository;
    private final CanSessionRepository canSessionRepository;
    private final IntegrityFaultRepository integrityFaultRepository;

    // ── Create ────────────────────────────────────────────────────────────────

    /**
     * Create a new car from a validated request.
     * carUid is auto-generated by CarEntity.prePersist() if not provided.
     *
     * @param request     validated create request (make, model, year required)
     * @param ownerUserId caller's user ID as BINARY(16) byte array — may be null
     * @return CarDto representing the saved car
     */
    @Transactional
    public CarDto createCar(CarCreateRequest request, byte[] ownerUserId) {
        CarEntity car = CarEntity.builder()
                .vin(request.getVin())
                .make(request.getMake())
                .model(request.getModel())
                .year(request.getYear())
                .color(request.getColor())
                .isVirtual(Boolean.TRUE.equals(request.getIsVirtual()))
                .isActive(true)
                .ownerUserId(ownerUserId)
                .build();

        CarEntity saved = carRepository.save(car);
        log.info("Car created: carUid={} make={} model={}", saved.getCarUid(), saved.getMake(), saved.getModel());
        return toDto(saved);
    }

    // ── Read ──────────────────────────────────────────────────────────────────

    /**
     * Get all active non-deleted cars owned by a specific user.
     *
     * @param ownerUserId user's binary(16) ID
     * @return list of CarDto (without computed stats)
     */
    public List<CarDto> getCarsByUser(byte[] ownerUserId) {
        return carRepository
                .findByOwnerUserIdAndIsActiveTrueAndDeletedAtIsNull(ownerUserId)
                .stream()
                .map(this::toDto)
                .toList();
    }

    /**
     * Get all active non-deleted cars (admin view).
     *
     * @return list of CarDto ordered by creation date descending
     */
    public List<CarDto> getAllCars() {
        return carRepository.findAllActive()
                .stream()
                .map(this::toDto)
                .toList();
    }

    /**
     * Get a single car by its public UUID.
     * Throws 404 if not found or soft-deleted.
     *
     * @param carUid public UUID string
     * @return CarDto with computed stats populated
     */
    public CarDto getCarByUid(String carUid) {
        CarEntity car = findActiveByUid(carUid);
        CarDto dto = toDto(car);
        populateStats(dto, car.getId());
        return dto;
    }

    // ── Stats ─────────────────────────────────────────────────────────────────

    /**
     * Populate sessionCount, totalFrames, lastSessionAt, and faultRate
     * on an existing CarDto using aggregation queries.
     *
     * @param dto   the CarDto to enrich
     * @param carId internal DB id of the car
     */
    public void populateStats(CarDto dto, Long carId) {
        // JPQL aggregate queries return List<Object[]>
        // Each Object[] contains: [COUNT (Long), SUM (Long), MAX (LocalDateTime)]
        List<Object[]> results = canSessionRepository.getCarSessionStats(carId);

        if (results == null || results.isEmpty()) return;

        Object[] row = results.get(0);
        if (row == null || row.length < 3 || row[0] == null) return;

        try {
            long sessionCount = ((Number) row[0]).longValue();
            long totalFrames  = row[1] != null ? ((Number) row[1]).longValue() : 0L;
            LocalDateTime lastSessionAt = row[2] instanceof LocalDateTime ldt ? ldt : null;

            dto.setSessionCount((int) sessionCount);
            dto.setTotalFrames(totalFrames);
            dto.setLastSessionAt(lastSessionAt);

            // Fault rate: faults per 1000 frames
            if (totalFrames > 0) {
                long totalFaults = integrityFaultRepository.countFaultsByCarId(carId);
                dto.setFaultRate((double) totalFaults / totalFrames * 1000.0);
            }
        } catch (Exception e) {
            log.warn("Could not populate stats for carId={}: {}", carId, e.getMessage());
        }
    }

    // ── Update ────────────────────────────────────────────────────────────────

    /**
     * Update a car's mutable fields (PATCH semantics — only non-null fields applied).
     *
     * @param carUid  public UUID of the car to update
     * @param request fields to update (all optional)
     * @return updated CarDto
     */
    @Transactional
    public CarDto updateCar(String carUid, CarUpdateRequest request) {
        CarEntity car = findActiveByUid(carUid);

        if (request.getVin()      != null) car.setVin(request.getVin());
        if (request.getMake()     != null) car.setMake(request.getMake());
        if (request.getModel()    != null) car.setModel(request.getModel());
        if (request.getYear()     != null) car.setYear(request.getYear());
        if (request.getColor()    != null) car.setColor(request.getColor());
        if (request.getIsVirtual() != null) car.setIsVirtual(request.getIsVirtual());
        if (request.getIsActive()  != null) car.setIsActive(request.getIsActive());

        CarEntity saved = carRepository.save(car);
        log.info("Car updated: carUid={}", carUid);
        return toDto(saved);
    }

    // ── Delete (soft) ─────────────────────────────────────────────────────────

    /**
     * Soft-delete a car by setting deletedAt and isActive = false.
     * Sessions and frames are NOT deleted — historical data is preserved.
     *
     * @param carUid public UUID of the car to soft-delete
     */
    @Transactional
    public void softDeleteCar(String carUid) {
        CarEntity car = findActiveByUid(carUid);
        car.setDeletedAt(LocalDateTime.now());
        car.setIsActive(false);
        carRepository.save(car);
        log.info("Car soft-deleted: carUid={}", carUid);
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    /**
     * Find an active (non-deleted) car by carUid or throw 404.
     */
    private CarEntity findActiveByUid(String carUid) {
        return carRepository.findByCarUid(carUid)
                .filter(c -> c.getDeletedAt() == null)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND,
                        "Car not found: " + carUid
                ));
    }

    /**
     * Map CarEntity to CarDto (without computed stats).
     * Computed fields (sessionCount, totalFrames, faultRate) are left null
     * and populated separately by populateStats() when needed.
     */
    private CarDto toDto(CarEntity car) {
        return CarDto.builder()
                .carUid(car.getCarUid())
                .vin(car.getVin())
                .make(car.getMake())
                .model(car.getModel())
                .year(car.getYear())
                .color(car.getColor())
                .isVirtual(car.getIsVirtual())
                .isActive(car.getIsActive())
                .createdAt(car.getCreatedAt())
                .build();
    }
}
